### ISSUE TITLE
Bad Request from datastream still return xts

### ISSUE THREAD

**Issue by mbannert** [CharlesCara/DatastreamDSWS2R#10]
An empty request which returns the datastream key, which should technically be character. If so, detected empty series or any other kind of foul return would be easier. 

Currently the behavior is as follows 

```
xx <- ds$timeSeriesRequest(
  instrument = "SWHWWAR",
  startDate = "-30Y",
  endDate = "-0D",
  frequency = "D"
)

class(xx)
# returns 
[1] "xts" "zoo"


```

Shouldn't this be changed? Any other suggestions to detect foul returns easier in a list of returns?

**Comment by CharlesCara** [comment]
I use this behaviour as a feature rather an a bug,  since `instrument` can be a vector with both valid and invalid codes ie 
```
xx <- ds$timeSeriesRequest(
  instrument = c("S&PCOMP", "SWHWWAR"),
  startDate = "-10D",
  endDate = "-0D",
  frequency = "D"
)

xx
```

So knowing that the function will return an xts reduces downstream errors (at least for us!).  The test I use for an empty series is to check the number of rows returned, ie 

```
xx <- ds$timeSeriesRequest(
  instrument = "SWHWWAR",
  startDate = "-10D",
  endDate = "-0D",
  frequency = "D"
)

stopifnot(nrow(xx) != 0 )
```

**Comment by mbannert** [comment]
ok fine then. I did `nrow()` as well here. If that's the official way I am ok with it.
