### ISSUE TITLE
Request data on specific dates

### ISSUE THREAD

**Issue by miguellacerda** [CharlesCara/DatastreamDSWS2R#23]
I was wondering if it would be possible to add the functionality to allow users to pull data for a specified set of dates (not necessarily evenly spaced)... something mid-way between snapshotRequest and timeSeriesRequest. The simplest implementation might be to allow snapshotRequest to accept a vector of dates for its requestDate parameter.

**Comment by CharlesCara** [comment]
If you can produce a code snippet that makes necessary requests and combines the responses into the require format then we could incorporate it.

**Comment by CharlesCara** [comment]
Thinking about this further, the question is how the results of different dates would be bound together as snapshotRequest can and will return a table with multiple columns especially if you request multiple datatypes.  Since they can be combined in different ways, this is best left to the user to do as suits them.
